# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RubyNEAT -- Neural Evolution of Augmenting Topoligies (NEAT)
email: fred.mitchell@gmx.de
description: > # this means to ignore newlines until "baseurl:"
  Ruby Implementation of the Neural Evolution of Augmenting Topologies algorithm.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rubyneat.de" # the base hostname & protocol for your site
twitter_username: flajann
github_username:  flajann2

# Build settings
markdown: kramdown
